name: dart_exceptions
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
<<<<<<< HEAD
  http: ^1.6.0
=======
  http: ^1.2.2
>>>>>>> a45a5260260bb4e7c53854b2ca7f4220c9f2a968
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
